apiVersion: v1
kind: Service
metadata:
  labels:
    app: quickstart-utility-policies-ts
  name: bigid-quickstart-utility-policies-ts
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 8085
      targetPort: 8085
      name: http
  selector:
    app: quickstart-utility-policies-ts